FROM node:latest

WORKDIR /app

# Copiamos solo los archivos de dependencias primero
COPY package*.json ./

# Instalamos las dependencias DENTRO del contenedor
RUN npm install

# Copiamos el resto del código
COPY . .

EXPOSE 3000

CMD ["node", "server.js"]